### ISSUE TITLE
Package for Debian arm?

### ISSUE THREAD

**Issue by parduz** [kreijack/xlibinput_calibrator#7]
I'd (badly) need this program for a BeagleBone Black (arm-gnueabi-hf) running Debian 10, but i'm unable to find any package to _apt-get_ and i can't cross-compile it.

There's a way to have xlibinput_calibrator as a binary?

**Comment by MihirGrand** [comment]
Me too! I'm getting some error trying to compile it, would be great to get a pre-compiled installation

**Comment by kreijack** [comment]
Which kind of error are you getting ?

**Comment by MihirGrand** [comment]
@kreijack I don't remember, I'll try compiling it again and let you know the error, eventually I was also able to install it using sudo apt install xinput-calibrator, but I missed an important detail, it needs x11 to function.

Do you have any experience with libinput by any chance? I need to get my flutter app running on my raspberry pi 3b+ asap, and it does run using flutter-pi, but there's some issue with the touch display and only half the touch display works, can this be fixed by setting the calibration matrix through libinput (flutter-pi uses libinput)? I posted the issue in the forum at https://forums.raspberrypi.com/viewtopic.php?t=366698, but haven't got any response and it's very urgent. I know it's not quite related to your project but I'd be very grateful if you could help me out or guide me to any helpful resources! 

Edit - Its been resolved now, thanks though!

**Comment by kreijack** [comment]
@MihirGrand,
good to ear that you solved. However even xlibinput-calibrator needs X11.

**Comment by MihirGrand** [comment]
@kreijack indeed, I ended up manually calibrating libinput
