### ISSUE TITLE
Clarify license

### ISSUE THREAD

**Issue by Atemu** [kreijack/xlibinput_calibrator#8]
Since this is a derivative work of xinput_calibrator and xinput, you should probably explicitly license your parts under the x11 license too and add a LICENSE/COPYING file with the MIT/X11 license text.

Currently, the situation is a bit unclear, making this hard to package & distribute.

**Comment by kreijack** [comment]
I updated the source:
- add a LICENSE.txt file
- update the header of the files src/xinput.*
Let me know if this solve the issue

**Comment by Atemu** [comment]
Thanks!

I think that should clear it for inclusion into Nixpkgs.

Also thanks for building this, it's the only way I found to calibrate my tablet on GNOME wayland that works.  

Do you know whether there's a way to permanently apply the matrix other than creating a custom udev rule?  

Also, do you know why the cursor (the dot) is not calibrated? Is it because this only tweaks Xwayland only?

**Comment by kreijack** [comment]
Frankly speaking, as X11 user I never cared the Wayland use case.
However the world is going to Wayland, so I think we should care.

Could you open another issue to track this PR ? I am interested to work on it, and I would appreciate your help because you have an user case (and a hardware) to work with.

Regarding your question:
> Do you know whether there's a way to permanently apply the matrix other than creating a custom udev rule?

I think that the only way is to set the new matrix with xinput (which should update the libinput); but this works only in X...

We should create a command that uses libinput_device_config_calibration_set_matrix() to set the matrix...

**Comment by Atemu** [comment]
https://github.com/kreijack/xlibinput_calibrator/issues/9
